spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    platform: postgres
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
